addons:
  postgresql: 11.5
language: ruby
rvm:
 - 2.4.1
cache: bundler
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database fantasy_fortuneteller_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
